from advent_of_code.puzzles.year_2025.day_07 import process


def test_tachyon_manifold_resolver():
    tm = process.TachyonManifold.from_input("""\
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............""")
    tmr = process.TachyonManifoldResolver(tm)
    assert tmr.resolve() == (21, 40)
