from advent_of_code.puzzles.year_2025.day_07 import process


def test_tachyon_manifold_simulator():
    tm = process.TachyonManifold.from_input("""\
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............""")
    tmr = process.TachyonManifoldSimulator(tm)
    assert tmr.simulate() == (21, 40)
